jobs:
- job: PrepareMacBuild

  pool:
    vmImage: 'macOS-10.14'
    demands: msbuild

  steps:
  - checkout: self
    submodules: true

  - task: UseDotNet@2
    displayName: 'Install .NET Core 3.1.101'
    inputs:
      packageType: sdk
      version: '3.1.101'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: NuGetToolInstaller@1
    displayName: 'Use NuGet 5.4.0'
    inputs:
      versionSpec: 5.4.0

  - task: InstallAppleCertificate@2
    inputs:
      certSecureFile: 'Dev.p12'
      certPwd: '$(DevCertPwd)'
      keychain: 'temp'

  - task: InstallAppleProvisioningProfile@1
    inputs:
      provisioningProfileLocation: 'secureFiles'
      provProfileSecureFile: '0b4d25a7-8250-4ec1-bbae-6dde6271ead8.mobileprovision'

  - task: InstallAppleProvisioningProfile@1
    inputs:
      provisioningProfileLocation: 'secureFiles'
      provProfileSecureFile: '7651b03d-ed9e-44e8-882a-928a7f0b5215.mobileprovision'

  - task: InstallAppleProvisioningProfile@1
    inputs:
      provisioningProfileLocation: 'secureFiles'
      provProfileSecureFile: '39824897-47c7-4b5a-b439-b738319bf109.mobileprovision'

  - task: InstallAppleProvisioningProfile@1
    inputs:
      provisioningProfileLocation: 'secureFiles'
      provProfileSecureFile: 'b2503178-3599-453e-909f-0b9d05f21112.mobileprovision'

  # Install Mono
  - task: CmdLine@2
    displayName: 'Provisioning Mono SDK'
    inputs:
      script: 'cd ~;
              curl -O https://download.mono-project.com/archive/6.8.0/macos-10-universal/MonoFramework-MDK-6.8.0.96.macos10.xamarin.universal.pkg;
              sudo installer -pkg ~/MonoFramework-MDK-6.8.0.96.macos10.xamarin.universal.pkg -target /'

  # Azure DevOps hosted pool is still using an old version of Xamarin.iOS, 
  # so we will upgrade
  - task: CmdLine@2
    displayName: 'Provisioning Xamarin.iOS'
    inputs:
      script: 'cd ~;
              curl -O https://download.visualstudio.microsoft.com/download/pr/fc059472-448e-4680-a3cd-e3ba032991c2/5e6c319f2c189459903c2cb1aa8a69ee/xamarin.ios-13.10.0.17.pkg;
              sudo installer -pkg ~/xamarin.ios-13.10.0.17.pkg -target /'

  - task: CmdLine@2
    displayName: 'Provisioning Xamarin.Mac'
    inputs:
      script: 'cd ~;
              curl -O https://download.visualstudio.microsoft.com/download/pr/fc059472-448e-4680-a3cd-e3ba032991c2/242c2c9b3eadc57438516f5856f0ee10/xamarin.mac-6.10.0.17.pkg;
              sudo installer -pkg ~/xamarin.mac-6.10.0.17.pkg -target /'

  - task: CmdLine@2
    displayName: 'Provisioning Xamarin.Android'
    inputs:
      script: 'cd ~;
              curl -O https://download.visualstudio.microsoft.com/download/pr/fc059472-448e-4680-a3cd-e3ba032991c2/172ae06981e5555a4113c016179e6f2b/xamarin.android-10.1.3.7.pkg;
              sudo installer -pkg ~/xamarin.android-10.1.3.7.pkg -target /'

  - script: 'brew install gitversion --ignore-dependencies'
    displayName: 'Install GitVersion'

  # Print the current version of Xamarin.iOS
  - task: CmdLine@2
    displayName: 'Show Xamarin.iOS Version'
    inputs:
      script: '/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch --version'
